name = "AstrodynamicsUtilities"
uuid = "aaa49d15-c72f-43c6-a65a-172a55867cac"
authors = ["Dylan LaSalle"]
version = "0.0.1-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
