name = "AstrodynamicsUtilities"
uuid = "aaa49d15-c72f-43c6-a65a-172a55867cac"
version = "0.0.1-DEV"
authors = ["Dylan LaSalle"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
LinearAlgebra = "1.12.0"
StaticArrays = "1.9.15"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
